### Import Libraries.

In [1]:
import pandas as pd 
import numpy as np

In [14]:
from sklearn.neighbors import KNeighborsRegressor

from sklearn.metrics import r2_score
from sklearn.model_selection import cross_val_score, KFold
from sklearn.model_selection import GridSearchCV

### Overview of data.

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')

In [3]:
df.sample(5)

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
150,1.65660,0.0,19.58,0,0.871,6.122,97.3,1.6180,5,403,14.7,372.80,14.10,21.5
385,16.81180,0.0,18.10,0,0.700,5.277,98.1,1.4261,24,666,20.2,396.90,30.81,7.2
187,0.07875,45.0,3.44,0,0.437,6.782,41.1,3.7886,5,398,15.2,393.87,6.68,32.0
191,0.06911,45.0,3.44,0,0.437,6.739,30.8,6.4798,5,398,15.2,389.71,4.69,30.5
232,0.57529,0.0,6.20,0,0.507,8.337,73.3,3.8384,8,307,17.4,385.91,2.47,41.7

In [9]:
# separate the feature and target. 
X = df.iloc[ : , : 13]
y = df['medv']

In [4]:
## Apply KNN Regressor without Grid Search CV.

In [12]:
# Model object. 
knn_model1 = KNeighborsRegressor()

# kfold object. 
kfold = KFold(n_splits=5, shuffle=True, random_state=42)

# training using cross validation. 
scores = cross_val_score(knn_model1, X, y, cv=kfold, scoring='r2')

# scores. 
print('Mean of all the scores : ', np.mean(scores))

Mean of all the scores :  0.5383871944766712

In [13]:
## Apply using Grid Search CV.

In [16]:
# Model object. 
knn_model2 = KNeighborsRegressor()

# create the parameter dictionary. 
param_dict = {
    'n_neighbors' : [1, 3, 5, 7, 9, 8, 11, 10, 17, 16, 19],
    'weights' : ['uniform', 'distance'], 
    'algorithm' : ['ball_tree', 'kd_tree', 'brute'], 
    'p' : [1, 2]
}


# finding best parameters using grid search cv. 
gscv = GridSearchCV(knn_model2, param_grid=param_dict, cv=kfold, refit=True, verbose=2, scoring='r2')

# training.
gscv.fit(X, y)

Fitting 5 folds for each of 132 candidates, totalling 660 fits
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=9, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=8, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=11, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=16, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=19, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s

GridSearchCV(cv=KFold(n_splits=5, random_state=42, shuffle=True),
             estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [1, 3, 5, 7, 9, 8, 11, 10, 17, 16, 19],
                         'p': [1, 2], 'weights': ['uniform', 'distance']},
             scoring='r2', verbose=2)

In [17]:
# best estimator. 
gscv.best_estimator_

KNeighborsRegressor(algorithm='ball_tree', p=1, weights='distance')

In [18]:
# best score. 
gscv.best_score_

np.float64(0.6434974189445056)

In [20]:
# best parameters.
gscv.best_params_

{'algorithm': 'ball_tree', 'n_neighbors': 5, 'p': 1, 'weights': 'distance'}

In [24]:
# results of all the combination. 
all_results = pd.DataFrame(gscv.cv_results_)
all_results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005617,0.001792,0.004926,0.000622,ball_tree,1,1,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 1, '...",0.530020,0.537940,0.451603,0.515197,0.504100,0.507772,0.030426,82
1,0.002886,0.000667,0.003593,0.000620,ball_tree,1,1,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 1, '...",0.530020,0.537940,0.451603,0.515197,0.504100,0.507772,0.030426,82
2,0.002356,0.000319,0.002457,0.000188,ball_tree,1,2,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 1, '...",0.417921,0.390612,0.387220,0.354948,0.481086,0.406357,0.042368,118
3,0.002235,0.000113,0.002686,0.000435,ball_tree,1,2,distance,"{'algorithm': 'ball_tree', 'n_neighbors': 1, '...",0.417921,0.390612,0.387220,0.354948,0.481086,0.406357,0.042368,118
4,0.002594,0.000831,0.002923,0.000823,ball_tree,3,1,uniform,"{'algorithm': 'ball_tree', 'n_neighbors': 3, '...",0.665828,0.649155,0.441905,0.724596,0.475487,0.591394,0.111715,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127,0.003137,0.001114,0.006520,0.000790,brute,16,2,distance,"{'algorithm': 'brute', 'n_neighbors': 16, 'p':...",0.558132,0.555195,0.430019,0.517834,0.469283,0.506093,0.049798,90
128,0.002291,0.000256,0.004630,0.000349,brute,19,1,uniform,"{'algorithm': 'brute', 'n_neighbors': 19, 'p':...",0.582220,0.446973,0.374025,0.463371,0.382191,0.449756,0.074887,115
129,0.003094,0.001118,0.007247,0.000776,brute,19,1,distance,"{'algorithm': 'brute', 'n_neighbors': 19, 'p':...",0.626162,0.604485,0.477791,0.588587,0.519874,0.563380,0.055650,43
130,0.003670,0.000491,0.007451,0.001262,brute,19,2,uniform,"{'algorithm': 'brute', 'n_neighbors': 19, 'p':...",0.478369,0.377584,0.329080,0.407952,0.313062,0.381209,0.059211,130
131,0.003738,0.001336,0.008271,0.000860,brute,19,2,distance,"{'algorithm': 'brute', 'n_neighbors': 19, 'p':...",0.544388,0.528056,0.425651,0.502669,0.439584,0.488070,0.047394,99

In [29]:
# find most important features from the all results.
all_results[['param_algorithm',	'param_n_neighbors',	'param_p', 'param_weights', 'mean_test_score']].sort_values('mean_test_score',ascending=False)

    param_algorithm  param_n_neighbors  param_p param_weights  mean_test_score
53          kd_tree                  5        1      distance         0.643497
97            brute                  5        1      distance         0.643497
9         ball_tree                  5        1      distance         0.643497
57          kd_tree                  7        1      distance         0.637631
101           brute                  7        1      distance         0.637631
..              ...                ...      ...           ...              ...
34        ball_tree                 17        2       uniform         0.395704
78          kd_tree                 17        2       uniform         0.395704
42        ball_tree                 19        2       uniform         0.381209
86          kd_tree                 19        2       uniform         0.381209
130           brute                 19        2       uniform         0.381209

[132 rows x 5 columns]

`NOTE : ` we can also using predict function we can predict on new data bcs at the last it will train new model for best parameters and store it in there object that are used for prediction in future.